nb_events = {
    "next": "/api/v1/sites/siteslug/pages/events?__nonce=3OUjEzI6iyybc1F3sk6YrQ&__token=ADGvBW9wM69kUiss1KqTIyVeQ5M6OwiL6ttexRFnHK9m&starting=2013-03-01",
    "prev": None,
    "results": [
    {
        "id": 5,
        "slug": "the_event_of_the_year",
        "status": "expired",
        "site_slug": "example_event_id",
        "name": "The event of the year!",
        "headline": "The event of the year!",
        "title": "The event of the year!",
        "excerpt": None,
        "author_id": 65,
        "published_at": "2013-05-07T14:14:07-07:00",
        "external_id": None,
        "tags": ["funny"],
        "intro": "",
        "calendar_id": 1,
        "contact": {
            "name": "Event Creator",
            "phone": None,
            "show_phone": True,
            "email": "foobarevents@mailinator.com",
            "show_email": True
        },
        "start_time": "2013-05-08T18:00:00-00:00",
        "end_time": "2013-05-08T21:00:00-00:00",
        "time_zone": "Hawaii",
        "rsvp_form": {
            "phone": "hidden",
            "address": "hidden",
            "allow_guests": True,
            "accept_rsvps": True,
            "gather_volunteers": False
        },
        "capacity": 15,
        "show_guests": True,
        "venue": {
            "name": "",
            "address": {
                "address1": "",
                "address2": "",
                "address3": "",
                "city": "Pasadena",
                "state": "CA",
                "country_code": "US",
                "zip": "91101",
                "lat": "34.1427587",
                "lng": "-118.1386005"
            }
        },
        "autoresponse": {
            "broadcaster_id": None,
            "subject": None,
            "body": None
        },
        "shifts": [{
            "id": 1,
            "start_time": "2013-05-17T10:50:17-00:00",
            "end_time": "2013-05-17T11:55:17-00:00",
            "time_zone": "Hawaii",
            "goal": 15,
        }]
    },
    {
        "id": 3,
        "slug": "event",
        "status": "expired",
        "site_slug": "example_event_id",
        "name": "Foobar Event",
        "headline": "Foobar Event",
        "title": "Event - Foobar Softwares",
        "excerpt": None,
        "author_id": 9,
        "published_at": "2013-02-28T20:43:36-08:00",
        "external_id": None,
        "tags": [],
        "intro": None,
        "calendar_id": None,
        "contact": {
            "name": None,
            "phone": None,
            "show_phone": True,
            "email": None,
            "show_email": True
        },
        "start_time": "2013-03-01T18:00:00-00:00",
        "end_time": "2013-03-01T21:00:00-00:00",
        "time_zone": "Hawaii",
        "rsvp_form": {
            "phone": "hidden",
            "address": "hidden",
            "allow_guests": True,
            "accept_rsvps": True,
            "gather_volunteers": False
        },
        "capacity": 0,
        "show_guests": True,
        "venue": {
            "name": None,
            "address": None
        },
        "autoresponse": {
            "broadcaster_id": 2,
            "subject": "RSVP confirmation for event",
            "body": None
        },
        "shifts": None
    }
    ]
}


example_person = {
    "birthdate": None,
    "city_district": None,
    "civicrm_id": None,
    "county_district": None,
    "county_file_id": None,
    "created_at": "2018-05-19T14:38:12-07:00",
    "datatrust_id": None,
    "do_not_call": False,
    "do_not_contact": False,
    "dw_id": None,
    "email": "fake_Jezza_1_fake_Trotsky@fakemail.com",
    "email_opt_in": True,
    "employer": None,
    "external_id": None,
    "federal_district": None,
    "fire_district": None,
    "first_name": "fake_Jezza_1",
    "has_facebook": False,
    "id": 586,
    "is_twitter_follower": False,
    "is_volunteer": False,
    "judicial_district": None,
    "labour_region": None,
    "last_name": "fake_Trotsky",
    "linkedin_id": None,
    "mobile": None,
    "mobile_opt_in": True,
    "middle_name": "",
    "nbec_guid": None,
    "ngp_id": None,
    "note": None,
    "occupation": None,
    "party": None,
    "pf_strat_id": None,
    "phone": None,
    "precinct_id": None,
    "primary_address": {
        "address1": "1337 Funny Point Avenue",
        "address2": None,
        "address3": None,
        "city": "Richmond",
        "county": "Contra Costa",
        "state": "CA",
        "country_code": "US",
        "zip": "94806",
        "lat": "FAKE",
        "lng": "FAKE",
        "fips": None,
        "street_number": "FAKE",
        "street_prefix": None,
        "street_name": "Funny Point",
        "street_type": "Lol",
        "street_suffix": None,
        "unit_number": None,
        "zip4": None,
        "zip5": "94806",
        "sort_sequence": None,
        "delivery_point": None,
        "lot": None,
        "carrier_route": None
    },
    "profile_image_url_ssl": "",
    "recruiter_id": None,
    "rnc_id": None,
    "rnc_regid": None,
    "salesforce_id": None,
    "school_district": None,
    "school_sub_district": None,
    "sex": None,
    "signup_type": 0,
    "state_file_id": None,
    "state_lower_district": None,
    "state_upper_district": None,
    "support_level": None,
    "supranational_district": None,
    "tags": [
        "meeting_housing_060618",
        "national_member",
        "meeting_electoral_061818",
        "interest_housing",
        "meeting_convention_042918",
        "education_spring_school_030818"
    ],
    "twitter_id": None,
    "twitter_name": None,
    "updated_at": "2018-05-20T01:55:06-07:00",
    "van_id": None,
    "village_district": None,
    "ward": None,
    "work_phone_number": None
}

