# Generated by Django 2.0.9 on 2018-10-03 00:44

from django.db import migrations, models
import django.db.models.deletion
import socsign.signin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('public_hex', models.CharField(default=socsign.signin.models.random_hex, max_length=10, unique=True)),
                ('secret_hex', models.CharField(default=socsign.signin.models.random_hex, max_length=10)),
                ('event_id', models.CharField(max_length=64)),
                ('event_title', models.CharField(max_length=255)),
                ('variant', models.CharField(choices=[('standard', 'Standard'), ('labor', 'Labor')], default='standard', max_length=20, verbose_name='Variant')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InterestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.EventForm')),
            ],
        ),
        migrations.AddField(
            model_name='eventform',
            name='interest_choices',
            field=models.ManyToManyField(to='signin.InterestChoice'),
        ),
    ]
